version: "3.7"

services:

  #################################################################
  # Kong: The API Gateway
  #################################################################
  kong:
    image: kong:latest
    container_name: kong
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong_db
      KONG_PG_USER: kong_user
      KONG_PG_PASSWORD: kong_password
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    networks:
      - ntw-kong
      - ntw-log-kong

  #################################################################
  # Konga: Kong GUI
  #################################################################
  konga:
    image: pantsel/konga:next
    container_name: konga
    restart: on-failure
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong_user
      DB_PASSWORD: kong_password
      DB_DATABASE: konga_db
      NODE_ENV: production
    volumes:
      - ./konga-data:/app/kongadata
    ports:
      - 1337:1337
    networks:
      - ntw-kong

networks:
  ntw-kong:
    driver: bridge
  